apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: mongo-argo
spec:
  project: default
  source:
    repoURL: https://github.com/htoohtooaungcloud/acme-crop-k8s-setup.git
    targetRevision: HEAD 
    path: frontend-backend-mongo
  destination:
    server: https://kubernetes.default.svc
    namespace: my-mongoapp
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:     
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true